(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "coffee-mode")
(depends-on "dash")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "f")
(depends-on "feature-mode")
(depends-on "grizzl")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "rbenv")
(depends-on "robe")
(depends-on "rspec-mode")
(depends-on "s")
(depends-on "scss-mode")
(depends-on "smartparens")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")